### ISSUE TITLE
"Meta" helm chart for easy beginner setup

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/helm#5]
### Clear and concise description of the problem

- When showing off woodpecker it would be nice to say it's only one helm install away (possibly even with a optional Gitea instance).

- especially when working with "custom" tags (i.e. pull_XXXX, next-<hash> once that becomes a thing), keeping the agent and server in sync is benificcial if not required.

### Suggested solution

- Add a "meta" chart (chart of charts) referencing woodpecker-server and woodpecker-agent
- Provide either a values.yaml via chart with common "ready to go" settings or write docs referencing or including a "demo" or "production-light" setup.
- Write a Administrator Getting started

### Alternative

Just do some nice docs helping towards an easy setup for non-versed users (be it Kubernetes, helm or woodpecker itself)

### Additional context

It's just a nice to have, but would probably be a good addition after woodpecker-ci/helm#4 is done.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by babykart** [comment]
From my point of view, I think the umbrella chart approach (chart of charts) is the best in the sense that there is no rewriting to do but just adding a third one (called _woodpecker-stack_ for example) including server and agent with minimal setup.
This will also keep more advanced users with more specific/exotic needs free to deploy only what they need...

An example of the Chart.yaml:

```yml
apiVersion: v2
name: woodpecker-stack
description: A Helm chart for the Woodpecker stack (server and agent)
type: application
version: 0.1.0
appVersion: "v1.0.0"

dependencies:
- name: woodpecker-server
  version: 0.1.0
  repository: https://woodpecker-ci.org
  condition: woodpecker-server.enabled
- name: woodpecker-agent
  version: 0.1.0
  repository: https://woodpecker-ci.org
  condition: woodpecker-agent.enabled

keywords:
- continuous-delivery
- continuous-deployment
- continuous-integration
- docker
- go
- kubernetes

sources:
- https://github.com/woodpecker-ci/woodpecker

maintainers:
- name: Woodpecker Maintainers
  email: owner@woodpecker-ci.org
```

values.yaml:

```yml
woodpecker-server:
  enabled: true
  <...>
woodpecker-agent:
  enabled: true
  <...>
```

The `condition` would clearly be optional because users could use the server and/or agent charts separately.
This umbrella chart would be easy to updated with the CI at every server and/or agent update.
